### ISSUE TITLE
Vehicle Stops Too Late / Cross Red Light

### ISSUE THREAD

**Issue by kkweon** [lucav76/CarND-Capstone#14]
The vehicle stops after the line.
![image](https://user-images.githubusercontent.com/2981167/34427929-3978d5b0-ebfc-11e7-934f-3146bd32af34.png)

or sometimes it cross the red light
when it happens, the log looks like this. 

```
ros_1  | Resize to (300, 300)
ros_1  | ('Boxes: ', array([[   0.        ,  145.37561035,   84.40847778,  178.70265198],
ros_1  |        [   0.        ,    2.73541284,   79.72753906,   21.94922447]], dtype=float32))
ros_1  | ('Boxes Ascending: ', [array([  0.        ,   2.73541284,  79.72753906,  21.94922447], dtype=float32), array([   0.        ,  145.37561035,   84.40847778,  178.70265198], dtype=float32)])
ros_1  | Raw predictions: [[  1.81863399e-10   3.07246239e-07   1.89774555e-15   9.99999642e-01
ros_1  |     5.03174995e-08   1.02036132e-07   1.94836357e-19   5.46941789e-12
ros_1  |     1.68915478e-12]]
ros_1  | +++ Accepting size:2772 - Prediction: Red
ros_1  | ('Timing: ', 144, 3)
ros_1  | [INFO] [1514514276.035685]: TL_DETECTOR: NNState: 0
ros_1  | Resize to (300, 300)
ros_1  | [INFO] [1514514276.193153]: TL_DETECTOR: NNState: -1
ros_1  | [INFO] [1514514276.193812]: TL_DETECTOR: Unknown State from classifier
ros_1  | Resize to (300, 300)
ros_1  | [INFO] [1514514276.353685]: TL_DETECTOR: NNState: -1
ros_1  | [INFO] [1514514276.353926]: TL_DETECTOR: Unknown State from classifier
ros_1  | Resize to (300, 300)
ros_1  | [INFO] [1514514276.513682]: TL_DETECTOR: NNState: -1
ros_1  | [INFO] [1514514276.513927]: TL_DETECTOR: Unknown State from classifier
ros_1  | Resize to (300, 300)
ros_1  | [INFO] [1514514276.673223]: TL_DETECTOR: NNState: -1
ros_1  | [INFO] [1514514276.673486]: TL_DETECTOR: Unknown State from classifier
ros_1  | Resize to (300, 300)
ros_1  | [INFO] [1514514276.831196]: TL_DETECTOR: NNState: -1
ros_1  | [INFO] [1514514276.831454]: TL_DETECTOR: Unknown State from classifier
ros_1  | Resize to (300, 300)
```

**Comment by Krishtof-Korda** [comment]
This should fixed it. 

https://github.com/lucav76/CarND-Capstone/pull/17/commits/c8cf14d9ecbfb31d6b3bfd7d9483e615a0536bc9

**Comment by kkweon** [comment]
Testing with current #17 and #18, I am still getting the same behavior (the vehicle does not stop the red light). 
It only happens only at the first signal.
From the second signal, the vehicle stops when it's the red light.

<div align="center">
<img src="https://user-images.githubusercontent.com/2981167/34449930-5c9d2462-ecb3-11e7-99a8-879bc7d9b201.gif" alt="Cross Red Light" width="100%"/>
</div>

**Comment by Krishtof-Korda** [comment]
I'm thinking this is highly dependent on the performance of the machine. On my machine I can't run the NN at all, the car doesn't move until I turn off the NN. 

Is anyone else (@jocmom @lucav76 @TimSoft77 ) still experiencing late stops or first red missed?

**Comment by jocmom** [comment]
Maybe it has something to do with the EARLY_STOP_STEPS. Will check this now.

**Comment by jocmom** [comment]
The waypoint updater uses the suggested waypoint velocity as reference and not the current velocity of the car, therefore it might think that the first stop line is too close or rather the deaccelaration value is too high. Especially when `early_stop` is activated .

**Comment by kkweon** [comment]
As @jocmom  points out, it seems 

```python
decel_rate = car_vel**2/(2*dist) 

if decel_rate < MAX_DECEL: # Drive right through the light if it's too close
    ...
```
(in [waypoint_updater.py](https://github.com/lucav76/CarND-Capstone/blob/master/ros/src/waypoint_updater/waypoint_updater.py#L82-L97))

is causing it. I will check increasing MAX_DECEL fix the issue.

**Comment by kkweon** [comment]
Yes increasing `MAX_DECEL` works. But during the acceleration phase, it will go beyond the speed limit, which will be fixed by @Krishtof-Korda  according to the slack message.

I'll send a PR fixing the MAX_DECEL

**Comment by kkweon** [comment]
#21 is merged, hence closing the issue for now.
