### ISSUE TITLE
Vehicle does not follow the speed limit?

### ISSUE THREAD

**Issue by kkweon** [lucav76/CarND-Capstone#20]
## Current Behavior
- The speed limit is set to 40 kph(≈ **24.8548 mph**)  in [this file](https://github.com/lucav76/CarND-Capstone/blob/master/ros/src/waypoint_loader/launch/waypoint_loader.launch#L5)
- The vehicle drives over the limit
    <div align="center">
    <img width="50%" src="https://user-images.githubusercontent.com/2981167/34450034-444868ac-ecb5-11e7-86d3-e52cf5386404.png" alt="Speed Limit" />
    </div>
- But it seems it's already implemented in [here](https://github.com/lucav76/CarND-Capstone/blob/master/ros/src/waypoint_updater/waypoint_updater.py#L90). Not sure why it's happening. :thinking: 
- **The vehicle only drove above the speed limit when running the red light (related issue #14)** After that, it slows down to the speed limit. It might indicate there is a problem with the initial launch.

## Expected Behavior
- The vehicle follows the parameter written in [waypoint_loader.launch](https://github.com/lucav76/CarND-Capstone/blob/master/ros/src/waypoint_loader/launch/waypoint_loader.launch#L5)

**Comment by Krishtof-Korda** [comment]
Anyone else  (@jocmom @lucav76 @TimSoft77 ) experiencing this?

**Comment by Krishtof-Korda** [comment]
Adjusted gains to maintain speed better. Fixed in commit: bccb4e07b02ceb3aa25b151911380fa1d6a0bbb7
