### ISSUE TITLE
Remove "jerky" acceleration

### ISSUE THREAD

**Issue by kkweon** [lucav76/CarND-Capstone#25]
## Summary
- The acceleration is not constant, but it's "pumping" according to the reviewer
- Still needs to investigate what causing it

**Comment by TimSoft77** [comment]
In my new `taDebug` branch, I've managed to eliminate the "pumping" issue when running against ground_truth data.  Notable changes:
1. Accel pid controller constants changed.  This was the primary fix for the "pumping" issue.  I think our primary problem was the gains were too high.
2. `waypoint_updater.py` changed to use the current velocity to choose the deceleration rate, (not just decide if to stop), and decelerate linearly to EARLY_STOP_DIST meters ahead of the traffic light.
3. `tl_detector.py` altered to use ground_truth data - do not merge this with `master`.

If someone else can test, feel free to merge the changes to `master` except those to `tl_detector.py`.
